package main

import "testing"

// TestVerifyDjangoPasswordCrossCheck uses a real hash generated by the
// actual installed Django version's make_password() (not a live user's
// credential — a throwaway test string), to make sure the Go port matches
// Django's own PBKDF2PasswordHasher byte-for-byte, not just an
// independently-reasoned reimplementation of the same spec.
func TestVerifyDjangoPasswordCrossCheck(t *testing.T) {
	const password = "correct horse battery staple"
	const djangoHash = "pbkdf2_sha256$1200000$0uc5kS3YE2l0XYosItGDnS$sFWg33oHQ58agxttlZMObBSzss9FTtXvgZdfJa6XSCE="

	if !verifyDjangoPassword(password, djangoHash) {
		t.Fatal("verifyDjangoPassword rejected a hash actually produced by Django's own make_password()")
	}
	if verifyDjangoPassword("wrong password", djangoHash) {
		t.Fatal("verifyDjangoPassword accepted an incorrect password")
	}
}

func TestHashAndVerifyDjangoPasswordRoundTrip(t *testing.T) {
	hash, err := hashDjangoPassword("another test password")
	if err != nil {
		t.Fatalf("hashDjangoPassword: %v", err)
	}
	if !verifyDjangoPassword("another test password", hash) {
		t.Fatal("verifyDjangoPassword rejected a hash this same package just created")
	}
	if verifyDjangoPassword("wrong", hash) {
		t.Fatal("verifyDjangoPassword accepted a wrong password against a freshly created hash")
	}
}

func TestVerifyDjangoPasswordRejectsUnsupportedAlgorithm(t *testing.T) {
	if verifyDjangoPassword("x", "argon2$argon2id$v=19$m=102400,t=2,p=8$salt$hash") {
		t.Fatal("verifyDjangoPassword should fail closed for algorithms other than pbkdf2_sha256")
	}
}
