package main

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"
)

// Export temp files are shared by every user of a server-mode instance (one
// temp directory per install), so each one is tied to the user who
// generated it: its name carries 128 random bits (the old timestamp-only
// names were guessable) and exportFileOwners records who may download,
// save or discard it. Ownership lives in memory only — after a restart old
// exports simply become unreachable until cleanTempFolder removes them,
// which is fine for files that only ever live for one download.
var (
	exportFileOwnersMu sync.Mutex
	exportFileOwners   = map[string]int{}
)

// newExportTempFile reserves a fresh, owner-tagged file name in tempDir with
// the given extension, creating tempDir (0700) if needed.
func newExportTempFile(tempDir string, userID int, ext string) (name, path string, err error) {
	if err := os.MkdirAll(tempDir, 0o700); err != nil {
		return "", "", err
	}
	// MkdirAll leaves an existing directory's mode alone; older installs
	// created it 0755.
	_ = os.Chmod(tempDir, 0o700)
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		return "", "", err
	}
	name = fmt.Sprintf("%d_%s.%s", time.Now().Unix(), hex.EncodeToString(buf), ext)
	exportFileOwnersMu.Lock()
	for k := range exportFileOwners {
		if _, err := os.Stat(filepath.Join(tempDir, k)); os.IsNotExist(err) {
			delete(exportFileOwners, k)
		}
	}
	exportFileOwners[name] = userID
	exportFileOwnersMu.Unlock()
	return name, filepath.Join(tempDir, name), nil
}

// exportFileOwnedBy reports whether name (a bare file name inside the temp
// directory) was generated by userID in this process.
func exportFileOwnedBy(name string, userID int) bool {
	exportFileOwnersMu.Lock()
	defer exportFileOwnersMu.Unlock()
	owner, ok := exportFileOwners[name]
	return ok && owner == userID
}

// createPrivateFile creates (or truncates) path readable only by this OS
// user — query exports can contain anything the database holds.
func createPrivateFile(path string) (*os.File, error) {
	return os.OpenFile(path, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0o600)
}
