package main

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"sync"
	"time"
)

// Export temp files are shared by every user of a server-mode instance (one
// temp directory per install), so each one is tied to the user who
// generated it: its name carries 128 random bits (the old timestamp-only
// names were guessable) and exportFileOwners records who may download,
// save or discard it. Ownership lives in memory only — after a restart old
// exports simply become unreachable until cleanTempFolder removes them,
// which is fine for files that only ever live for one download.
var (
	exportFileOwnersMu sync.Mutex
	exportFileOwners   = map[string]int{}
)

// newExportTempFile reserves a fresh, owner-tagged file name in tempDir with
// the given extension, creating tempDir (0700) if needed.
func newExportTempFile(tempDir string, userID int, ext string) (name, path string, err error) {
	if err := os.MkdirAll(tempDir, 0o700); err != nil {
		return "", "", err
	}
	// MkdirAll leaves an existing directory's mode alone; older installs
	// created it 0755.
	_ = os.Chmod(tempDir, 0o700)
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		return "", "", err
	}
	name = fmt.Sprintf("%d_%s.%s", time.Now().Unix(), hex.EncodeToString(buf), ext)
	exportFileOwnersMu.Lock()
	for k := range exportFileOwners {
		if _, err := os.Stat(filepath.Join(tempDir, k)); os.IsNotExist(err) {
			delete(exportFileOwners, k)
		}
	}
	exportFileOwners[name] = userID
	exportFileOwnersMu.Unlock()
	return name, filepath.Join(tempDir, name), nil
}

// exportFileOwnedBy reports whether name (a bare file name inside the temp
// directory) was generated by userID in this process.
func exportFileOwnedBy(name string, userID int) bool {
	_, ok := exportFileTrustedName(name, userID)
	return ok
}

// exportFileTrustedName returns the registry's own copy of name when userID
// generated it. Callers build filesystem paths from this server-generated
// key rather than from the request-supplied string that merely matched it.
func exportFileTrustedName(name string, userID int) (string, bool) {
	exportFileOwnersMu.Lock()
	defer exportFileOwnersMu.Unlock()
	for k, owner := range exportFileOwners {
		if k == name && owner == userID {
			return k, true
		}
	}
	return "", false
}

// createPrivateFile creates (or truncates) path readable only by this OS
// user — query exports can contain anything the database holds.
func createPrivateFile(path string) (*os.File, error) {
	return os.OpenFile(path, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0o600)
}

// writeExportTextFile stores one generated text document as a temp export
// file owned by userID and answers with the same {v_filename, v_filepath,
// v_downloadname} shape export.go's responses carry, so the frontend's
// deliverExportFile (export_file.js) can drive the native Save dialog
// (desktop) / download link (browser) for it. Used by the exports that are
// always exactly one text blob (DBML, permissions script).
func writeExportTextFile(w http.ResponseWriter, upstream *url.URL, userID int, content, ext, downloadName string) {
	tempDir, err := resolveTempDir(upstream)
	if err != nil {
		writeDatabaseError(w, err.Error())
		return
	}
	cleanTempFolder(tempDir.TempDir)

	fileName, outPath, err := newExportTempFile(tempDir.TempDir, userID, ext)
	if err != nil {
		writeDatabaseError(w, err.Error())
		return
	}
	if err := os.WriteFile(outPath, []byte(content), 0o600); err != nil {
		writeDatabaseError(w, err.Error())
		return
	}

	writeEnvelope(w, map[string]any{
		"v_filename":     tempDir.Path + "/static/temp/" + fileName,
		"v_filepath":     outPath,
		"v_downloadname": downloadName,
	}, false, -1)
}
