package main

import (
	"database/sql"
	"fmt"
)

// postgresqlDDLClass mirrors PostgreSQL.py's GetDDLClass (PostgreSQL 12+
// branch) — used for table/index/view/sequence/mview/foreign_table DDL.
// It's one big pg_dump-style CTE query that already does 100% of the work
// entirely in SQL; the Go side's job is just to run it and hand back the
// resulting text, exactly like PostgreSQL.py's ExecuteScalar call did.
func postgresqlDDLClass(db *sql.DB, schema, object string) (string, error) {
	var ddl sql.NullString
	err := db.QueryRow(`
				with obj as (
				   SELECT c.oid,
						 'pg_class'::regclass,
						 c.relname AS name,
						 n.nspname AS namespace,
						 coalesce(cc.column2,c.relkind::text) AS kind,
						 pg_get_userbyid(c.relowner) AS owner,
						 coalesce(cc.column2,c.relkind::text) AS sql_kind,
						 cast($1::regclass AS text) AS sql_identifier
					FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
					LEFT join (
						 values ('r','TABLE'),
								('v','VIEW'),
								('i','INDEX'),
								('I','PARTITIONED INDEX'),
								('S','SEQUENCE'),
								('s','SPECIAL'),
								('m','MATERIALIZED VIEW'),
								('c','TYPE'),
								('t','TOAST'),
								('f','FOREIGN TABLE'),
								('p','PARTITIONED TABLE')
					) as cc on cc.column1 = c.relkind
				   WHERE c.oid = $1::regclass
				),
				columns as (
					SELECT a.attname AS name, format_type(t.oid, NULL::integer) AS type,
						CASE
							WHEN (a.atttypmod - 4) > 0 THEN a.atttypmod - 4
							ELSE NULL::integer
						END AS size,
						a.attnotnull AS not_null,
						a.attgenerated AS generated,
						pg_get_expr(def.adbin, def.adrelid) AS "default",
						col_description(c.oid, a.attnum::integer) AS comment,
						con.conname AS primary_key,
						a.attislocal AS is_local,
						a.attstorage::text AS storage,
						nullif(col.collcollate::text,'') AS collation,
						a.attnum AS ord,
						s.nspname AS namespace,
						c.relname AS class_name,
						format('%s.%I',text(c.oid::regclass),a.attname) AS sql_identifier,
						c.oid,
						a.attacl,
						format('%I %s%s%s%s',
							a.attname::text,
							format_type(t.oid, a.atttypmod),
					        CASE
						      WHEN length(col.collcollate) > 0
							  THEN ' COLLATE ' || quote_ident(col.collcollate::text)
							  ELSE ''
							END,
							CASE
							  WHEN a.attnotnull THEN ' NOT NULL'::text
							  ELSE ''::text
							END,
							CASE
							  WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'::text
							  WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'::text
							  WHEN a.attgenerated = 's' THEN format(' GENERATED ALWAYS AS %s STORED',pg_get_expr(def.adbin, def.adrelid))::text
							  ELSE ''::text
							END)
						AS definition
				   FROM pg_class c
				   JOIN pg_namespace s ON s.oid = c.relnamespace
				   JOIN pg_attribute a ON c.oid = a.attrelid
				   LEFT JOIN pg_attrdef def ON c.oid = def.adrelid AND a.attnum = def.adnum
				   LEFT JOIN pg_constraint con
						ON con.conrelid = c.oid AND (a.attnum = ANY (con.conkey)) AND con.contype = 'p'
				   LEFT JOIN pg_type t ON t.oid = a.atttypid
				   LEFT JOIN pg_collation col ON col.oid = a.attcollation
				   JOIN pg_namespace tn ON tn.oid = t.typnamespace
				  WHERE c.relkind IN ('r','v','c','f','p') AND a.attnum > 0 AND NOT a.attisdropped
					AND has_table_privilege(c.oid, 'select') AND has_schema_privilege(s.oid, 'usage')
					AND c.oid = $1::regclass
				  ORDER BY s.nspname, c.relname, a.attnum
				),
				comments as (
				   select 'COMMENT ON COLUMN ' || text($1) || '.' || quote_ident(name) ||
						  E'\nIS ' || quote_nullable(comment) || ';' as cc
					 from columns
					where comment IS NOT NULL
				),
				settings as (
				   select 'ALTER ' || obj.kind || ' ' || text($1) || ' SET (' ||
						  quote_ident(option_name)||'='||quote_nullable(option_value) ||');' as ss
					 from pg_options_to_table((select reloptions from pg_class where oid = $1::regclass))
					 join obj on (true)
				),
				constraints as (
				   SELECT nc.nspname AS namespace,
						r.relname AS class_name,
						c.conname AS constraint_name,
						case c.contype
							when 'c'::"char" then 'CHECK'::text
							when 'f'::"char" then 'FOREIGN KEY'::text
							when 'p'::"char" then 'PRIMARY KEY'::text
							when 'u'::"char" then 'UNIQUE'::text
							when 't'::"char" then 'TRIGGER'::text
							when 'x'::"char" then 'EXCLUDE'::text
							else c.contype::text
						end AS constraint_type,
						pg_get_constraintdef(c.oid,true) AS constraint_definition,
						c.condeferrable AS is_deferrable,
						c.condeferred  AS initially_deferred,
						r.oid as regclass, c.oid AS sysid
				   FROM pg_namespace nc, pg_namespace nr, pg_constraint c, pg_class r
				  WHERE nc.oid = c.connamespace AND nr.oid = r.relnamespace AND c.conrelid = r.oid
					AND coalesce(r.oid=$1::regclass,true)
				),
				indexes as (
				   SELECT DISTINCT
						c.oid AS oid,
						n.nspname::text AS namespace,
						c.relname::text AS class,
						i.relname::text AS name,
						NULL::text AS tablespace,
						CASE d.refclassid
							WHEN 'pg_constraint'::regclass
							THEN 'ALTER TABLE ' || text(c.oid::regclass)
								 || ' ADD CONSTRAINT ' || quote_ident(cc.conname)
								 || ' ' || pg_get_constraintdef(cc.oid)
							ELSE pg_get_indexdef(i.oid)
						END AS indexdef,
						cc.conname::text AS constraint_name
				   FROM pg_index x
				   JOIN pg_class c ON c.oid = x.indrelid
				   JOIN pg_namespace n ON n.oid = c.relnamespace
				   JOIN pg_class i ON i.oid = x.indexrelid
				   JOIN pg_depend d ON d.objid = x.indexrelid
				   LEFT JOIN pg_constraint cc ON cc.oid = d.refobjid
				  WHERE c.relkind in ('r','p','m') AND i.relkind in ('i'::"char", 'I'::"char")
					AND coalesce(c.oid = $1::regclass,true)
					AND NOT x.indisunique
					AND NOT x.indisprimary
					AND NOT x.indisexclusion
				),
				triggers as (
				   SELECT
						CASE t.tgisinternal
							WHEN true THEN 'CONSTRAINT'::text
							ELSE NULL::text
						END AS is_constraint, t.tgname::text AS trigger_name,
						CASE (t.tgtype::integer & 64) <> 0
							WHEN true THEN 'INSTEAD'::text
							ELSE CASE t.tgtype::integer & 2
							  WHEN 2 THEN 'BEFORE'::text
							  WHEN 0 THEN 'AFTER'::text
							  ELSE NULL::text
							END
						END AS action_order,
						array_to_string(array[
						  case when (t.tgtype::integer &  4) <> 0 then 'INSERT'   end,
						  case when (t.tgtype::integer &  8) <> 0 then 'DELETE'   end,
						  case when (t.tgtype::integer & 16) <> 0 then 'UPDATE'   end,
						  case when (t.tgtype::integer & 32) <> 0 then 'TRUNCATE' end
						],' OR ') AS event_manipulation,
						c.oid::regclass::text AS event_object_sql_identifier,
						p.oid::regprocedure::text AS action_statement,
						CASE t.tgtype::integer & 1
							WHEN 1 THEN 'ROW'::text
							ELSE 'STATEMENT'::text
						END AS action_orientation,
						pg_get_triggerdef(t.oid,true) as trigger_definition,
						c.oid::regclass AS regclass,
						p.oid::regprocedure AS regprocedure,
						s.nspname::text AS event_object_schema,
						c.relname::text AS event_object_table,
						(quote_ident(t.tgname::text) || ' ON ') || c.oid::regclass::text AS sql_identifier
				   FROM pg_trigger t
				   LEFT JOIN pg_class c ON c.oid = t.tgrelid
				   LEFT JOIN pg_namespace s ON s.oid = c.relnamespace
				   LEFT JOIN pg_proc p ON p.oid = t.tgfoid
				   LEFT JOIN pg_namespace s1 ON s1.oid = p.pronamespace
				   WHERE coalesce(c.oid=$1::regclass,true)
				),
				rules as (
				   SELECT n.nspname::text AS namespace,
						c.relname::text AS class_name,
						r.rulename::text AS rule_name,
						CASE
							WHEN r.ev_type = '1'::"char" THEN 'SELECT'::text
							WHEN r.ev_type = '2'::"char" THEN 'UPDATE'::text
							WHEN r.ev_type = '3'::"char" THEN 'INSERT'::text
							WHEN r.ev_type = '4'::"char" THEN 'DELETE'::text
							ELSE 'UNKNOWN'::text
						END AS rule_event,
						r.is_instead,
						pg_get_ruledef(r.oid, true) AS rule_definition,
						c.oid::regclass AS regclass
				   FROM pg_rewrite r
				   JOIN pg_class c ON c.oid = r.ev_class
				   JOIN pg_namespace n ON n.oid = c.relnamespace
				  WHERE coalesce(c.oid=$1::regclass,true)
					AND NOT (r.ev_type = '1'::"char" AND r.rulename = '_RETURN'::name)
				  ORDER BY r.oid
				),
				createview as (
					select
					 'CREATE '||
					  case relkind
						when 'v' THEN 'OR REPLACE VIEW '
						when 'm' THEN 'MATERIALIZED VIEW '
					  end || (oid::regclass::text) || E' AS\n'||
					  pg_catalog.pg_get_viewdef(oid,true)||E'\n'||
					  (CASE WHEN obj_description($1::regclass, 'pg_class') IS NOT NULL
							THEN (CASE relkind WHEN 'v'
											   THEN format(
														E'\n\nCOMMENT ON VIEW %s\nIS %s;',
														$1::regclass,
														quote_literal(obj_description($1::regclass, 'pg_class'))
													)
											   WHEN 'm'
											   THEN format(
														E'\n\nCOMMENT ON MATERIALIZED VIEW %s\nIS %s;',
														$1::regclass,
														quote_literal(obj_description($1::regclass, 'pg_class'))
													)
											   ELSE ''
								  END)
							ELSE ''
					   END) as text
					 FROM pg_class t
					 WHERE oid = $1::regclass
					   AND relkind in ('v','m')
				),
				createtable as (
					select
						'CREATE '||
					  case relpersistence
						when 'u' then 'UNLOGGED '
						when 't' then 'TEMPORARY '
						else ''
					  end
					  || case obj.kind when 'PARTITIONED TABLE' then 'TABLE' else obj.kind end || ' ' || obj.sql_identifier
					  || case obj.kind when 'TYPE' then ' AS' else '' end
					  || case when c.relispartition
					  then
						  E'\n' ||
						  (SELECT
							 coalesce(' PARTITION OF ' || string_agg(i.inhparent::regclass::text,', '), '')
							 FROM pg_inherits i WHERE i.inhrelid = $1::regclass) ||
						  E'\n'||
							coalesce(' '||(
							  pg_get_expr(c.relpartbound, c.oid, true)
							),'')
					  else
						  E' (\n'||
							coalesce(''||(
							  SELECT coalesce(string_agg('    '||definition,E',\n'),'')
								FROM columns WHERE is_local
							)||E'\n','')||')'
						  ||
						  (SELECT
							coalesce(' INHERITS(' || string_agg(i.inhparent::regclass::text,', ') || ')', '')
							 FROM pg_inherits i WHERE i.inhrelid = $1::regclass)
					  end
					  ||
					  case when c.relkind = 'p'
					  then E'\n' || ' PARTITION BY ' || pg_get_partkeydef($1::regclass)
					  else '' end
					  ||
					  coalesce(
						E'\nSERVER '||quote_ident(fs.srvname)
						,'')
					  ||
					  coalesce(
						E'\nOPTIONS (\n'||
						(select string_agg(
								  '    '||quote_ident(option_name)||' '||quote_nullable(option_value),
								  E',\n')
						   from pg_options_to_table(ft.ftoptions))||E'\n)'
						,'')
					  ||
					  E';\n'||
					  (CASE WHEN obj_description($1::regclass, 'pg_class') IS NOT NULL
							THEN (CASE relkind WHEN 'r'
											   THEN format(
														E'\n\nCOMMENT ON TABLE %s\nIS %s;',
														$1::regclass,
														quote_literal(obj_description($1::regclass, 'pg_class'))
													)
											   WHEN 'p'
											   THEN format(
														E'\n\nCOMMENT ON TABLE %s\nIS %s;',
														$1::regclass,
														quote_literal(obj_description($1::regclass, 'pg_class'))
													)
											   WHEN 'f'
											   THEN format(
														E'\n\nCOMMENT ON FOREIGN TABLE %s\nIS %s;',
														$1::regclass,
														quote_literal(obj_description($1::regclass, 'pg_class'))
													)
											   ELSE ''
								  END)
							ELSE ''
					   END) as text
					 FROM pg_class c JOIN obj ON (true)
					 LEFT JOIN pg_foreign_table  ft ON (c.oid = ft.ftrelid)
					 LEFT JOIN pg_foreign_server fs ON (ft.ftserver = fs.oid)
					 WHERE c.oid = $1::regclass
					-- AND relkind in ('r','c')
				),
				createsequence as (
					SELECT 'CREATE SEQUENCE '||(c.oid::regclass::text) || E';\n'
						   ||'ALTER SEQUENCE '||(c.oid::regclass::text)
						   ||E'\n INCREMENT BY '||sp.increment
						   ||E'\n MINVALUE '||sp.minimum_value
						   ||E'\n MAXVALUE '||sp.maximum_value
						   ||E'\n START WITH '||sp.start_value
						   ||E'\n '|| CASE cycle_option WHEN true THEN 'CYCLE' ELSE 'NO CYCLE' END
						   ||E';\n'||
						   (CASE WHEN obj_description($1::regclass, 'pg_class') IS NOT NULL
								 THEN (CASE relkind WHEN 'S'
													THEN format(
															 E'\n\nCOMMENT ON SEQUENCE %s\nIS %s;',
															 $1::regclass,
															 quote_literal(obj_description($1::regclass, 'pg_class'))
														 )
													ELSE ''
									   END)
								 ELSE ''
							END) as text
					FROM pg_class c,
					LATERAL pg_sequence_parameters(c.oid) sp (start_value, minimum_value, maximum_value, increment, cycle_option)
					WHERE c.oid = $1::regclass
					  AND c.relkind = 'S'
				),
				createindex as (
					with ii as (
					 SELECT DISTINCT CASE d.refclassid
								WHEN 'pg_constraint'::regclass
								THEN 'ALTER TABLE ' || text(c.oid::regclass)
									 || ' ADD CONSTRAINT ' || quote_ident(cc.conname)
									 || ' ' || pg_get_constraintdef(cc.oid)
								ELSE pg_get_indexdef(i.oid) ||
									 (CASE WHEN obj_description($1::regclass, 'pg_class') IS NOT NULL
										   THEN format(
													E'\n\nCOMMENT ON INDEX %s\nIS %s;',
													$1::regclass,
													quote_literal(obj_description($1::regclass, 'pg_class'))
												)
										   ELSE ''
									  END)
							END AS indexdef
					   FROM pg_index x
					   JOIN pg_class c ON c.oid = x.indrelid
					   JOIN pg_class i ON i.oid = x.indexrelid
					   JOIN pg_depend d ON d.objid = x.indexrelid
					   LEFT JOIN pg_constraint cc ON cc.oid = d.refobjid
					  WHERE c.relkind in ('r','p','m') AND i.relkind in ('i'::"char", 'I'::"char")
						AND i.oid = $1::regclass
					)
					 SELECT indexdef || E';\n' as text
					   FROM ii
				),
				createclass as (
					select format(E'--\n-- Type: %s ; Name: %s; Owner: %s\n--\n\n', obj.kind,obj.name,obj.owner)
					||
					 case
					  when obj.kind in ('VIEW','MATERIALIZED VIEW') then (select text from createview)
					  when obj.kind in ('TABLE','TYPE','FOREIGN TABLE','PARTITIONED TABLE') then (select text from createtable)
					  when obj.kind in ('SEQUENCE') then (select text from createsequence)
					  when obj.kind in ('INDEX', 'PARTITIONED INDEX') then (select text from createindex)
					  else '-- UNSUPPORTED CLASS: '||obj.kind
					 end
					  || E'\n' ||
					  coalesce((select string_agg(cc,E'\n')||E'\n' from comments),'')
					  ||
					  coalesce(E'\n'||(select string_agg(ss,E'\n')||E'\n' from settings),'')
					  || E'\n' as text
					from obj
				),
				altertabledefaults as (
					select
						coalesce(
						  string_agg(
							'ALTER TABLE '||text($1)||
							  ' ALTER '||quote_ident(name)||
							  ' SET DEFAULT '||"default",
							E';\n') || E';\n\n',
						'') as text
					   from columns
					  where "default" is not null
						and generated = ''
				),
				createconstraints as (
					with cs as (
					  select
					   'ALTER TABLE ' || text(regclass(regclass)) ||
					   ' ADD CONSTRAINT ' || quote_ident(constraint_name) ||
					   E'\n  ' || constraint_definition as sql
						from constraints
					   order by constraint_type desc, sysid
					 )
					 select coalesce(string_agg(sql,E';\n') || E';\n\n','') as text
					   from cs
				),
				createindexes as (
					with ii as (select * from indexes order by name)
					 SELECT coalesce(string_agg(indexdef||E';\n','') || E'\n' , '') as text
					   FROM ii
					  WHERE constraint_name is null
				),
				createtriggers as (
					with tg as (
					  select trigger_definition as sql
					 from triggers where is_constraint is null
					 order by trigger_name
					 -- per SQL triggers get called in order created vs name as in PostgreSQL
					 )
					 select coalesce(string_agg(sql,E';\n')||E';\n\n','') as text
					   from tg
				),
				createrules as (
					select coalesce(string_agg(rule_definition,E'\n')||E'\n\n','') as text
					from rules
				   where regclass = $1::regclass
					 and rule_definition is not null
				),
				alterowner as (
					select
					   case
						 when obj.kind in ('INDEX', 'PARTITIONED INDEX') then ''
						 when obj.kind = 'PARTITIONED TABLE'
						 then 'ALTER TABLE '||sql_identifier||
							  ' OWNER TO '||quote_ident(owner)||E';\n\n'
						 else 'ALTER '||sql_kind||' '||sql_identifier||
							  ' OWNER TO '||quote_ident(owner)||E';\n\n'
					   end as text
					  from obj
				),
				privileges as (
					SELECT (u_grantor.rolname)::information_schema.sql_identifier AS grantor,
							(grantee.rolname)::information_schema.sql_identifier AS grantee,
							(current_database())::information_schema.sql_identifier AS table_catalog,
							(nc.nspname)::information_schema.sql_identifier AS table_schema,
							(c.relname)::information_schema.sql_identifier AS table_name,
							(c.prtype)::information_schema.character_data AS privilege_type,
							(
								CASE
									WHEN (pg_has_role(grantee.oid, c.relowner, 'USAGE'::text) OR c.grantable) THEN 'YES'::text
									ELSE 'NO'::text
								END)::information_schema.yes_or_no AS is_grantable,
							(
								CASE
									WHEN (c.prtype = 'SELECT'::text) THEN 'YES'::text
									ELSE 'NO'::text
								END)::information_schema.yes_or_no AS with_hierarchy
						   FROM ( SELECT pg_class.oid,
										 pg_class.relname,
										 pg_class.relnamespace,
										 pg_class.relkind,
										 pg_class.relowner,
										 (aclexplode(COALESCE(pg_class.relacl, acldefault('r', pg_class.relowner)))).grantor AS grantor,
										 (aclexplode(COALESCE(pg_class.relacl, acldefault('r', pg_class.relowner)))).grantee AS grantee,
										 (aclexplode(COALESCE(pg_class.relacl, acldefault('r', pg_class.relowner)))).privilege_type AS privilege_type,
										 (aclexplode(COALESCE(pg_class.relacl, acldefault('r', pg_class.relowner)))).is_grantable AS is_grantable
								  FROM pg_class
								  WHERE pg_class.relkind <> 'S'
								  UNION
								  SELECT pg_class.oid,
										 pg_class.relname,
										 pg_class.relnamespace,
										 pg_class.relkind,
										 pg_class.relowner,
										 (aclexplode(COALESCE(pg_class.relacl, acldefault('S', pg_class.relowner)))).grantor AS grantor,
										 (aclexplode(COALESCE(pg_class.relacl, acldefault('S', pg_class.relowner)))).grantee AS grantee,
										 (aclexplode(COALESCE(pg_class.relacl, acldefault('S', pg_class.relowner)))).privilege_type AS privilege_type,
										 (aclexplode(COALESCE(pg_class.relacl, acldefault('S', pg_class.relowner)))).is_grantable AS is_grantable
								  FROM pg_class
								  WHERE pg_class.relkind = 'S') c(oid, relname, relnamespace, relkind, relowner, grantor, grantee, prtype, grantable),
							pg_namespace nc,
							pg_roles u_grantor,
							( SELECT pg_roles.oid,
									pg_roles.rolname
								   FROM pg_roles
								UNION ALL
								 SELECT (0)::oid AS oid,
									'PUBLIC'::name) grantee(oid, rolname)
						  WHERE ((c.relnamespace = nc.oid) AND (c.grantee = grantee.oid) AND (c.grantor = u_grantor.oid)
							AND (c.prtype = ANY (ARRAY['INSERT'::text, 'SELECT'::text, 'UPDATE'::text, 'DELETE'::text, 'TRUNCATE'::text, 'REFERENCES'::text, 'TRIGGER'::text]))
							AND (pg_has_role(u_grantor.oid, 'USAGE'::text) OR pg_has_role(grantee.oid, 'USAGE'::text) OR (grantee.rolname = 'PUBLIC'::name)))
				),
				grants as (
					select
					   coalesce(
						string_agg(format(
							E'GRANT %s ON %s TO %s%s;\n',
							privilege_type,
							$1,
							case grantee
							  when 'PUBLIC' then 'PUBLIC'
							  else quote_ident(grantee)
							end,
							case is_grantable
							  when 'YES' then ' WITH GRANT OPTION'
							  else ''
							end), ''),
						'') as text
					 FROM privileges g
					 join obj on (true)
					 WHERE table_schema=obj.namespace
					   AND table_name=obj.name
					   AND grantee<>obj.owner
				),
				columnsprivileges as (
					SELECT r.rolname AS grantee,
						   c.name AS column_name,
						   c.privilege_type
					FROM (
						SELECT name,
							   (aclexplode(attacl)).grantee AS grantee,
							   (aclexplode(attacl)).privilege_type AS privilege_type
						FROM columns
					) c
					INNER JOIN pg_roles r
							ON c.grantee = r.oid
				),
				columnsgrants as (
					SELECT coalesce(
							   string_agg(
								   format(
									   E'GRANT %s(%s) ON %s TO %s;\n',
									   privilege_type,
									   column_name,
									   $1,
									   quote_ident(grantee)
								   ),
								   ''
							   ),
							   ''
						   ) AS text
					 FROM columnsprivileges
				)
				select (select text from createclass) ||
					   (select text from altertabledefaults) ||
					   (select text from createconstraints) ||
					   (select text from createindexes) ||
					   (select text from createtriggers) ||
					   (select text from createrules) ||
					   (select text from alterowner) ||
					   (select text from grants) ||
					   (SELECT text FROM columnsgrants)
	`, schema+"."+object).Scan(&ddl)
	if err != nil {
		return "", err
	}
	return ddl.String, nil
}

// postgresqlDDLTableField mirrors PostgreSQL.py's GetDDLTableField
// (PostgreSQL 13+ branch).
//
// The column filter is `quote_ident(a.attname) = $1`, not raw
// `a.attname = $1` — see postgresqlPropertiesTableField's comment
// (postgresql_properties.go) for why: p_column arrives already
// quote_ident()-quoted, same as p_schema/p_table, so comparing it to the
// raw catalog value only worked by accident for names that don't need
// quoting. A column needing quoting (mixed case, reserved word) used to
// make the DDL tab fail to find the column at all.
func postgresqlDDLTableField(db *sql.DB, schema, table, column string) (string, error) {
	var ddl sql.NullString
	err := db.QueryRow(`
					WITH columns AS (
						SELECT format(
								   '%I %s%s%s%s',
								   a.attname::text,
								   format_type(t.oid, a.atttypmod),
								   (CASE WHEN length(col.collcollate) > 0
										 THEN ' COLLATE ' || quote_ident(col.collcollate::text)
										 ELSE ''
									END),
								   (CASE WHEN a.attnotnull
										 THEN ' NOT NULL'::text
										 ELSE ''::text
									END),
								   (CASE WHEN a.attidentity = 'a'
										 THEN ' GENERATED ALWAYS AS IDENTITY'::text
										 WHEN a.attidentity = 'd'
										 THEN ' GENERATED BY DEFAULT AS IDENTITY'::text
										 WHEN a.attgenerated = 's'
										 THEN format(' GENERATED ALWAYS AS %s STORED', pg_get_expr(def.adbin, def.adrelid))::text
										 ELSE ''::text
									END)
							   ) AS definition,
							   a.attname AS name,
							   col_description(c.oid, a.attnum::integer) AS comment,
							   pg_get_expr(def.adbin, def.adrelid) AS default_value,
							   a.attgenerated AS generated,
							   a.attacl
						FROM pg_class c
						INNER JOIN pg_namespace s
								ON s.oid = c.relnamespace
						INNER JOIN pg_attribute a
								ON c.oid = a.attrelid
						LEFT JOIN pg_attrdef def
							   ON c.oid = def.adrelid
							  AND a.attnum = def.adnum
						LEFT JOIN pg_constraint con
							   ON con.conrelid = c.oid
							  AND (a.attnum = ANY (con.conkey))
							  AND con.contype = 'p'
						LEFT JOIN pg_type t
							   ON t.oid = a.atttypid
						LEFT JOIN pg_collation col
							   ON col.oid = a.attcollation
						INNER JOIN pg_namespace tn
								ON tn.oid = t.typnamespace
						WHERE c.relkind IN ('r', 'p')
						  AND a.attnum > 0
						  AND NOT a.attisdropped
						  AND has_table_privilege(c.oid, 'select')
						  AND has_schema_privilege(s.oid, 'usage')
						  AND c.oid = $2::regclass
						  AND quote_ident(a.attname) = $1
					),
					comments AS (
						SELECT format(
								   E'\n\nCOMMENT ON COLUMN %s.%s\nIS %s;',
								   $2,
								   quote_ident(name),
								   quote_nullable(comment)
							   ) AS definition
						FROM columns
						WHERE comment IS NOT NULL
					),
					defaults AS (
						SELECT format(
								   E'\n\nALTER TABLE %s\n\tALTER %s SET DEFAULT %s;',
								   $2::regclass,
								   quote_ident(name),
								   default_value
							   ) AS definition
						FROM columns
						WHERE default_value IS NOT NULL
						  AND generated = ''
					),
					columnsprivileges as (
						SELECT r.rolname AS grantee,
							   c.name AS column_name,
							   c.privilege_type
						FROM (
							SELECT name,
								   (aclexplode(attacl)).grantee AS grantee,
								   (aclexplode(attacl)).privilege_type AS privilege_type
							FROM columns
						) c
						INNER JOIN pg_roles r
								ON c.grantee = r.oid
					),
					columnsgrants as (
						SELECT coalesce(
								   nullif(
									   format(
										   E'\n\n%s',
										   string_agg(
											   format(
												   E'GRANT %s(%s) ON %s TO %s;\n',
												   privilege_type,
												   column_name,
												   $2,
												   quote_ident(grantee)
											   ),
											   ''
										   )
									   ),
									   '\n\n'
								   ),
								   ''
							   ) AS definition
						 FROM columnsprivileges
					)
					SELECT format(
								E'ALTER TABLE %s\n\tADD COLUMN %s;%s%s%s',
								$2::regclass,
								col.definition,
								coalesce(com.definition, ''),
								coalesce(def.definition, ''),
								coalesce(cg.definition, '')
						   )
					FROM columns col
					LEFT JOIN comments com
						   ON 1 = 1
					LEFT JOIN defaults def
						   ON 1 = 1
					LEFT JOIN columnsgrants cg
						   ON 1 = 1
	`, column, schema+"."+table).Scan(&ddl)
	if err != nil {
		return "", err
	}
	return ddl.String, nil
}

// postgresqlDDLTrigger mirrors PostgreSQL.py's GetDDLTrigger.
func postgresqlDDLTrigger(db *sql.DB, schema, table, trigger string) (string, error) {
	var ddl sql.NullString
	err := db.QueryRow(`
			select 'CREATE TRIGGER ' || x.trigger_name || chr(10) ||
				   '  ' || x.action_timing || ' ' || x.event_manipulation || (CASE WHEN x.columns IS NOT NULL THEN ' OF ' || x.columns ELSE '' END) || chr(10) ||
				   '  ON ' || $4::regclass::text || chr(10) ||
				   '  FOR EACH ' || x.action_orientation || chr(10) ||
				   (case when length(coalesce(x.action_condition, '')) > 0 then '  WHEN ( ' || x.action_condition || ') ' || chr(10) else '' end) ||
				   '  ' || x.action_statement || ';' ||
				   (CASE WHEN obj_description(x.oid, 'pg_trigger') IS NOT NULL
						 THEN format(
								 E'\n\nCOMMENT ON TRIGGER %s ON %s\nIS %s;',
								 x.trigger_name,
								 $4::regclass::text,
								 quote_literal(obj_description(x.oid, 'pg_trigger'))
							 )
						 ELSE ''
					END) as definition
			from (
			select distinct quote_ident(t.trigger_name) as trigger_name,
				   t.action_timing,
				   e.event as event_manipulation,
				   t.action_orientation,
				   t.action_condition,
				   t.action_statement,
				   t2.oid,
				   tuc.columns
			from information_schema.triggers t
			inner join (
			select array_to_string(array(
			select event_manipulation::text
			from information_schema.triggers
			where quote_ident(event_object_schema) = $1
			  and quote_ident(event_object_table) = $2
			  and quote_ident(trigger_name) = $3
			), ' OR ') as event
			) e ON 1 = 1
			INNER JOIN (
				SELECT oid
				FROM pg_trigger
				WHERE quote_ident(tgname) = $3
					AND tgrelid = $4::regclass
			) AS t2 ON 1 = 1
			LEFT JOIN (
				SELECT string_agg(
						   event_object_column,
						   ', '
					   ) AS columns
				FROM information_schema.triggered_update_columns
				WHERE quote_ident(event_object_schema) = $1
				  AND quote_ident(event_object_table) = $2
				  AND quote_ident(trigger_name) = $3
			) tuc
				   ON 1 = 1
			WHERE quote_ident(t.event_object_schema) = $1
				AND quote_ident(t.event_object_table) = $2
				AND quote_ident(t.trigger_name) = $3
			) x
	`, schema, table, trigger, schema+"."+table).Scan(&ddl)
	if err != nil {
		return "", err
	}
	return ddl.String, nil
}

// postgresqlDDLConstraint mirrors PostgreSQL.py's GetDDLConstraint — used
// for pk/foreign_key/unique (and check/exclude, not yet exposed by any Go
// route) DDL.
func postgresqlDDLConstraint(db *sql.DB, schema, table, object string) (string, error) {
	var ddl sql.NullString
	err := db.QueryRow(`
			with cs as (
			  select
			   'ALTER TABLE ' || text(regclass(c.conrelid)) ||
			   ' ADD CONSTRAINT ' || quote_ident(c.conname) ||
			   E'\n  ' || pg_get_constraintdef(c.oid, true) as sql,
			   c.oid,
			   c.conname,
			   c.conrelid
				from pg_constraint c
			   join pg_class t
			   on t.oid = c.conrelid
			   join pg_namespace n
			   on t.relnamespace = n.oid
			   where quote_ident(n.nspname) = $1
				 and quote_ident(t.relname) = $2
				 and quote_ident(c.conname) = $3
			),
			comments AS (
				SELECT format(
						   E'COMMENT ON CONSTRAINT %s ON %s\nIS %s;',
						   quote_ident(conname),
						   conrelid::regclass,
						   quote_literal(x.description)
					   ) AS sql
				FROM (
					SELECT oid,
						   conname,
						   conrelid,
						   obj_description(oid, 'pg_constraint') AS description
					FROM cs
				) x
				WHERE x.description IS NOT NULL
			)
			select format(
					   E'%s%s',
					   coalesce(string_agg(cs.sql,E';\n') || E';\n\n',''),
					   coalesce(c.sql, '')
				   ) as text
			from cs cs
			LEFT JOIN comments c
				   ON 1 = 1
			GROUP BY cs.sql,
					 c.sql
	`, schema, table, object).Scan(&ddl)
	if err != nil {
		return "", err
	}
	return ddl.String, nil
}

// postgresqlDDLDatabase synthesizes a CREATE DATABASE statement. Unlike
// every other DDL helper in this file, Postgres has no pg_get_*def()-style
// function for a database's own definition, so this builds the statement
// from pg_database directly — the same OWNER/ENCODING/LC_COLLATE/LC_CTYPE/
// TABLESPACE/CONNECTION LIMIT clauses pgAdmin and DBeaver generate.
func postgresqlDDLDatabase(db *sql.DB, name string) (string, error) {
	var owner, encoding, collate, ctype, tablespace string
	var connLimit int64
	err := db.QueryRow(`
		select pg_catalog.pg_get_userbyid(d.datdba) as owner,
			   pg_catalog.pg_encoding_to_char(d.encoding) as encoding,
			   d.datcollate,
			   d.datctype,
			   coalesce(t.spcname, 'pg_default') as tablespace,
			   d.datconnlimit
		from pg_catalog.pg_database d
		left join pg_catalog.pg_tablespace t on t.oid = d.dattablespace
		where quote_ident(d.datname) = $1
	`, name).Scan(&owner, &encoding, &collate, &ctype, &tablespace, &connLimit)
	if err != nil {
		return "", err
	}

	return fmt.Sprintf(
		"CREATE DATABASE %s\n"+
			"    WITH\n"+
			"    OWNER = %s\n"+
			"    ENCODING = '%s'\n"+
			"    LC_COLLATE = '%s'\n"+
			"    LC_CTYPE = '%s'\n"+
			"    TABLESPACE = %s\n"+
			"    CONNECTION LIMIT = %d;",
		name,
		quotePostgresIdentifierDoubleQuoted(owner),
		encoding, collate, ctype,
		quotePostgresIdentifierDoubleQuoted(tablespace),
		connLimit,
	), nil
}
