// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FrontendReady() {
  return window['go']['main']['App']['FrontendReady']();
}

export function RestoreWindowState() {
  return window['go']['main']['App']['RestoreWindowState']();
}
